name: Linter

on: push

jobs:
  app-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make install
        run: make install

      - name: Make lint
        run: make lint

      - name: Make test
        run: make test
